export const SET_LOCALE = 'SET_LOCALE';

export const FETCH_SHOWS_REQUEST = 'FETCH_SHOWS_REQUEST';
export const FETCH_SHOWS_SUCCESS = 'FETCH_SHOWS_SUCCESS';
export const FETCH_SHOWS_ERROR = 'FETCH_SHOWS_ERROR';
