export const SET_LOCALE = 'SET_LOCALE';

export const FETCH_SHOWS_REQUEST = 'FETCH_SHOWS_REQUEST';
export const FETCH_SHOWS_SUCCESS = 'FETCH_SHOWS_SUCCESS';
export const FETCH_SHOWS_ERROR = 'FETCH_SHOWS_ERROR';

export const AUTH_USER_REQUEST = 'AUTH_USER_REQUEST';
export const AUTH_USER_SUCCESS = 'AUTH_USER_SUCCESS';
export const AUTH_USER_ERROR = 'AUTH_USER_ERROR';

export const GET_AUTHORIZEDUSER_REQUEST = 'GET_AUTHORIZEDUSER_REQUEST';
export const GET_AUTHORIZEDUSER_SUCCESS = 'GET_AUTHORIZEDUSER_SUCCESS';
export const GET_AUTHORIZEDUSER_ERROR = 'GET_AUTHORIZEDUSER_ERROR';

export const AUTH_USER_LOGOUT_REQUEST = 'AUTH_USER_LOGOUT_REQUEST';
export const AUTH_USER_LOGOUT_SUCCESS = 'AUTH_USER_LOGOUT_SUCCESS';
export const AUTH_USER_LOGOUT_ERROR = 'AUTH_USER_LOGOUT_ERROR';
